version: "3.9"
services:
  web:
    build: 
      context: .
      args:
        - PORT=3000
    image: developer-portfolio:${TAG:-latest}
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - type: bind
        source: /Flash/DerekMackley/developer-portfolio/site.conf
        target: /etc/nginx/conf.d/site.conf
        read_only: true
      - type: bind
        source: /Flash/DerekMackley/developer-portfolio/files
        target: /app/files
        read_only: true
    environment:
      - NODE_ENV=production
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - portfolio_net

networks:
  portfolio_net:
    driver: bridge
    internal: false
    driver_opts:
      com.docker.network.bridge.name: portfolio_net
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
