{{- if .Values.mainApp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainApp.name }}
  labels:
    app: {{ .Values.mainApp.name }}
    chart: {{ include "developer-portfolio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.mainApp.service.type }}
  ports:
    - port: {{ .Values.mainApp.service.port }}
      targetPort: {{ .Values.mainApp.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.mainApp.name }}
    release: {{ .Release.Name }}
{{- end }}