source "https://rubygems.org"

# Jekyll
gem "jekyll", "~> 4.3.0"

# Theme
gem "minima", "~> 2.5"

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :mswin, :x64_mingw]

# Required for Ruby 3.4+ compatibility
gem "csv"
gem "logger"
gem "base64"

# Lock http_parser.rb gem to v0.6.x on JRuby builds since newer versions
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]