name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # Step 1: Run tests
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  
  # Step 2: Run linting
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  
  # Step 3: Build and push Docker image if on master branch
  deploy-docker:
    name: Deploy Docker Image
    needs: [test, lint]
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/docker-build.yml
  
  # Step 4: Deploy documentation if the docs folder changed
  deploy-docs:
    name: Deploy Documentation
    needs: [test, lint]
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deploy-docs.yml
    with:
      check_changes: true