name: Deploy Documentation

on:
  workflow_call:
    inputs:
      check_changes:
        description: 'Whether to check for changes in docs folder'
        type: boolean
        default: true
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'

jobs:
  check-changes:
    name: Check for docs changes
    runs-on: ubuntu-latest
    if: inputs.check_changes
    outputs:
      docs_changed: ${{ steps.changes.outputs.docs_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for docs changes
        id: changes
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "docs_changed=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_call" ]]; then
            echo "docs_changed=true" >> $GITHUB_OUTPUT
          else
            # Get changed files in docs/
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- docs/)
            if [[ -n "$CHANGED_FILES" ]]; then
              echo "docs_changed=true" >> $GITHUB_OUTPUT
            else
              echo "docs_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
          
          echo "Docs changed: ${{ steps.changes.outputs.docs_changed }}"

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [check-changes]
    if: |
      github.event_name == 'workflow_dispatch' || 
      github.event_name == 'push' || 
      (needs.check-changes.outputs.docs_changed == 'true')
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      
      - name: Setup Docsify
        run: yarn global add docsify-cli
      
      - name: Build documentation
        run: |
          mkdir -p build
          cp -r docs/* build/
          cp docs/index.md build/README.md || true
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          target-folder: docs
