name: Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install ESLint and plugins
        run: |
          npm install --save-dev eslint@8.57.0 eslint-plugin-react eslint-plugin-security
          
      - name: Create .eslintrc.json with environment globals for tests
        run: |
          echo '{
            "env": {
              "browser": true,
              "es2021": true,
              "node": true,
              "jest": true
            },
            "extends": [
              "eslint:recommended",
              "plugin:react/recommended"
            ],
            "parserOptions": {
              "ecmaFeatures": {
                "jsx": true
              },
              "ecmaVersion": "latest",
              "sourceType": "module"
            },
            "plugins": [
              "react",
              "security"
            ],
            "settings": {
              "react": {
                "version": "detect"
              }
            },
            "rules": {
              "react/prop-types": "warn",
              "react/jsx-uses-react": "error",
              "react/jsx-uses-vars": "error",
              "no-unused-vars": "warn",
              "no-undef": "warn",
              "security/detect-object-injection": "warn"
            }
          }' > .eslintrc.json
          
      - name: Verify ESLint configuration
        run: |
          echo "ESLint configuration file contents:"
          cat .eslintrc.json
          echo ""
          echo "ESLint version:"
          npx eslint --version
          
      - name: Run linting with npx and continue on error
        run: npx eslint src --ext .js,.jsx || true