name: Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines
      
      - name: Run tests
        run: yarn test
